(function(){function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function l(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function ba(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}function n(a){return a instanceof Array?a:ba(l(a))}function p(){}var q=[];
function ca(a,b){if(!b||"function"!==typeof b)return!1;try{var c=""+b}catch(h){return!1}var d=c.length;if(d>35+a.length)return!1;for(var e=d-13,f=0,g=8;g<d;g+=1){f="[native code]"[f]===c[g]||7===f&&"-"===c[g]?f+1:0;if(12===f)return!0;if(!f&&g>e)break}return!1}function r(a,b){var c=ca(a,b);b&&!c&&q.push([a,b]);return c}function t(a,b){return r(b,a)&&a}var da=t(String.prototype.indexOf,"indexOf");
function ea(a,b){for(var c=0,d=a.length-b.length,e=0;e<a.length;e+=1){c=a[e]===b[c]?c+1:0;if(c===b.length)return e-b.length+1;if(!c&&e>d)break}return-1}var fa=da?function(a,b){return da.call(a,b)}:ea;function ha(a,b){return!(!a||-1===fa(a,b))}function ia(a){return"[object Array]"===Object.prototype.toString.call(a)}var ja=t(Array.isArray,"isArray"),ka=ja?function(a){return ja(a)}:ia;function la(a,b){return b(a)}function v(a){return function(b){return function(c){return a(b,c)}}}
function w(a){return function(b){return function(c){return a(c,b)}}}var ma=v(function(a,b){return a===b}),x=v(la),na=ma(null);function y(a){return"function"===typeof a}var z=ma(void 0);function A(a){return z(a)||na(a)}var oa=t(Array.from,"from");function pa(a){for(var b=a.length,c=[],d=0;d<b;d+=1)c.push(a[d]);return c}function B(a){if(oa)try{return oa(a)}catch(b){}return pa(a)}
function qa(a,b,c){b=void 0===b?[]:b;c=c||{};var d=b.length,e=a;y(e)&&(e="d",c[e]=a);var f;d?1===d?f=c[e](b[0]):2===d?f=c[e](b[0],b[1]):3===d?f=c[e](b[0],b[1],b[2]):4===d&&(f=c[e](b[0],b[1],b[2],b[3])):f=c[e]();return f}var ta=t(Function.prototype.bind,"bind");
function ua(){var a=B(arguments);a=l(a);var b=a.next().value,c=a.next().value,d=ba(a);return function(){var e=[].concat(n(d),n(B(arguments)));if(Function.prototype.call)return Function.prototype.call.apply(b,[c].concat(n(e)));if(c){for(var f="_b";c[f];)f+="_"+f.length;c[f]=b;e=c[f]&&qa(f,e,c);delete c[f];return e}return qa(b,e)}}var C=ta?function(){var a=B(arguments),b=l(a);a=b.next().value;var c=b.next().value;b=ba(b);return ta.apply(a,[c].concat(b))}:ua;
function D(a,b){return C.apply(null,[b,null].concat(n(a)))}function E(a,b){return C(b,null,a)}function F(a,b){return C(b[a],b)}var va=t(Array.prototype.reduce,"reduce");function wa(a,b,c){for(var d=0,e=c.length;d<e;)b=a(b,c[d],d),d+=1;return b}var G=va?function(a,b,c){return va.call(c,a,b)}:wa,xa=Object.prototype.hasOwnProperty;function H(a,b){return A(a)?!1:xa.call(a,b)}function I(a,b){return a?G(function(c,d){if(A(c))return c;try{return c[d]}catch(e){}return null},a,b.split(".")):null}var J=w(I);
function ya(a,b){for(var c=0;c<b.length;c+=1)if(b[c]===a)return c;return-1}var za;function Aa(a){if(za)return za;var b=!1;try{b=[].indexOf&&0===[void 0].indexOf(void 0)}catch(d){}var c=a.Array&&a.Array.prototype&&t(a.Array.prototype.indexOf,"indexOf");return za=a=b&&c?function(d,e){return c.call(e,d)}:ya}var Ba=Aa(window);function K(a){return a}function L(a,b){return b}function Ca(a){return!a}
function M(a,b){var c=[],d=[];var e=b?b:K;return function(){var f=B(arguments),g=e.apply(null,n(f)),h=Ba(g,d);if(-1!==h)return c[h];f=a.apply(null,n(f));c.push(f);d.push(g);return f}}var Da=M(J("navigator.userAgent")),Ea=/Firefox\/([0-9]+)/i,Fa=M(function(a){var b=I(a,"document.documentElement.style"),c=I(a,"InstallTrigger");a=-1!==(I(a,"navigator.userAgent")||"").toLowerCase().search(Ea);Ea.lastIndex=0;return!(!(b&&"MozAppearance"in b)||A(c))||a});
function Ga(a,b){var c=I(b,a),d=I(b,"constructor.prototype."+a)||c;try{if(d&&d.apply)return function(){return d.apply(b,arguments)}}catch(e){return c}return d}function Ha(){var a=Array.prototype.map;if(!Fa(window))return!0;try{a.call({0:!0,length:-Math.pow(2,32)+1},function(){throw 1;})}catch(b){return!1}return!0}var Ia=t(Array.prototype.map,"map");function Ja(a,b){return G(function(c,d,e){c.push(a(d,e));return c},[],b)}var N=Ia&&Ha()?function(a,b){return b&&0<b.length?Ia.call(b,a):[]}:Ja,Ka=w(N);
function O(){var a=B(arguments),b=a.shift();return function(){var c=b.apply(null,arguments);return G(la,c,a)}}var La=v(D),Ma=v(F);function Na(a,b,c){return c?a:b}var Oa=D([1,null],Na);D([1,0],Na);var Pa=Boolean,Qa=t(Array.prototype.filter,"filter");function Ra(a,b){return wa(function(c,d,e){a(d,e)&&c.push(d);return c},[],b)}var Sa=Qa?function(a,b){return Qa.call(b,a)}:Ra,Ta=E(Pa,Sa),Ua=t(Array.prototype.includes,"includes");function Va(a,b){return 1<=Ra(ma(a),b).length}
var Wa=Ua?function(a,b,c){return Ua.call(b,a,c)}:Va;function Xa(a){return a?ka(a)?a:oa?oa(a):"number"===typeof a.length&&0<=a.length?pa(a):[]:[]}var Ya=t(Array.prototype.some,"some");function Za(a,b){for(var c=0;c<b.length;c+=1)if(c in b&&a.call(b,b[c],c))return!0;return!1}var $a=Ya?function(a,b){return Ya.call(b,a)}:Za,ab=w(parseInt)(10),bb=t(Object.keys,"keys");function cb(a){var b=[],c;for(c in a)H(a,c)&&b.push(c);return b}var db=t(Object.entries,"entries");
function eb(a){return z(a)?[]:wa(function(b,c){b.push([c,a[c]]);return b},[],cb(a))}var fb=db?function(a){return a?db(a):[]}:eb,gb=bb?function(a){return bb(a)}:cb;function hb(){var a=B(arguments),b=l(a);a=b.next().value;for(b=ba(b);b.length;){var c=b.shift(),d;for(d in c)H(c,d)&&(a[d]=c[d]);H(c,"toString")&&(a.toString=c.toString)}return a}
var P=Object.assign||hb,ib=M(O(J("String.fromCharCode"),E("fromCharCode",r),Ca)),jb=M(O(Da,F("test",/ipad|iphone|ipod/i))),kb=M(function(a){a=(Da(a)||"").toLowerCase();return ha(a,"android")&&ha(a,"mobile")}),lb=M(O(J("document.addEventListener"),Ca)),mb=M(function(a){return(I(a,"top")||a)!==a});J("top.contentWindow");var nb=M(function(a){var b=!1;try{b=a.navigator.javaEnabled()}catch(c){}return b});function ob(a){return jb(a)||kb(a)||/mobile/i.test(Da(a))||!z(I(a,"orientation"))}
var pb=M(function(a){a=!(!a.addEventListener||!a.removeEventListener);return{la:a,g:a?"addEventListener":"attachEvent",X:a?"removeEventListener":"detachEvent"}});function qb(a,b,c,d,e,f){a=pb(a);var g=a.g,h=a.X;f=f?h:g;if(b[f])if(a.la)if(e)b[f](c,d,e);else b[f](c,d);else b[f]("on"+c,d)}
var rb=M(function(a){var b=!1;if(!a.addEventListener)return b;try{var c=Object.defineProperty({},"passive",{get:function(){b=!0;return 1}});a.addEventListener("test",p,c)}catch(d){}return b}),sb=v(function(a,b){if(null!==b)return a?P({capture:!0,passive:!0},b||{}):!!b}),tb=M(function(a){var b=rb(a),c=sb(b),d={};return P(d,{g:function(e,f,g,h){N(function(k){var m=c(h);qb(a,e,k,g,m,!1)},f);return C(d.na,d,e,f,g,h)},na:function(e,f,g,h){N(function(k){var m=c(h);qb(a,e,k,g,m,!0)},f)}})});
function ub(a,b){N(O(K,F("push",a)),b)}var vb=M(function(a){a=a.Ya=a.Ya||{};var b=a._metrika=a._metrika||{};return{xa:function(c,d){H(b,c)||(b[c]=d);return this},B:function(c,d){b[c]=d;return this},l:function(c,d){var e=b[c];return H(b,c)||z(d)?e:d}}}),Q=M(function(a){return a.id+":"+a.T});function wb(a,b){for(var c="",d=0;d<b.length;d+=1)c+=""+(d?a:"")+b[d];return c}var xb=t(Array.prototype.join,"join"),R=xb?function(a,b){return xb.call(b,a)}:wb,yb="hash host hostname href pathname port protocol search".split(" ");
function U(a){return G(function(b,c){var d=I(a,"location."+c);b[c]=d?""+d:"";return b},{},yb)}var zb=/^\s+|\s+$/g,Ab=t(String.prototype.trim,"trim");function Bb(a){return Ab?Ab.call(a):(""+a).replace(zb,"")}var Cb=v(function(a,b){return b.replace(a,"")}),Db=Cb(/\s/g),V=Cb(/\D/g),Eb=["metrika_enabled"],Fb=[];function Gb(a,b){var c=Hb;return!Fb.length||Wa(b,Eb)?!0:G(function(d,e){return d&&e(a,c,b)},!0,Fb)}
function Ib(a){try{var b=a.document.cookie;if(!A(b)){var c={};N(function(d){var e=l(d.split("="));d=e.next().value;e=e.next().value;d=d?Bb(d):"";var f="";try{f=decodeURIComponent(e)}catch(g){}e=(e=f)?Bb(e):"";c[d]=e},(b||"").split(";"));return c}}catch(d){}return null}var Jb=function(a,b,c){return function(){var d=vb(arguments[0]),e=c?"global":"m2380",f=d.l(e,{}),g=I(f,a);g||(g=M(b),f[a]=g,d.B(e,f));return g.apply(null,arguments)}}("gsc",Ib);function Hb(a,b){var c=Jb(a);return c?c[b]||null:null}
var Kb=/:\d+$/;function Lb(a,b,c,d,e,f,g){g=void 0===g?!1:g;if(Gb(a,b)){var h=b+"="+encodeURIComponent(c)+";";if(d){var k=new Date;k.setTime(k.getTime()+6E4*d);h+="expires="+k.toUTCString()+";"}e&&(d=e.replace(Kb,""),h+="domain="+d+";");try{a.document.cookie=h+("path="+(f||"/")),g||(Jb(a)[b]=c)}catch(m){}}}
var Mb=M(function(a){var b=(U(a).host||"").split(".");return 1===b.length?b[0]:G(function(c,d,e){e+=1;2<=e&&!c&&(e=R(".",b.slice(-e)),Lb(a,"metrika_enabled","1",0,e,void 0,!0),(d=(d=Ib(a))&&d.metrika_enabled)&&Lb(a,"metrika_enabled","",-100,e,void 0,!0),d&&(c=e));return c},"",b)});
function Nb(a,b,c){b=void 0===b?"_ym_":b;c=void 0===c?"":c;var d=Mb(a),e=1===(d||"").split(".").length?d:"."+d,f=c?"_"+c:"";return{da:function(g,h,k){Lb(a,""+b+g+f,"",-100,h||e,k,!1);return this},l:function(g){return Hb(a,""+b+g+f)},B:function(g,h,k,m,u){Lb(a,""+b+g+f,h,k,m||e,u);return this}}}
var Ob=M(Nb),Pb=M(function(a){var b=Ob(a),c="1"===b.l("debug"),d=U(a).href;(d=-1<fa(d,"_ym_debug=1"))||(d=U(a).href,d=-1<fa(d,"_ym_debug=2"));var e=a._ym_debug;!e&&!d||c||(a=U(a),b.B("debug","1",void 0,a.host));return!!(c||e||d)});lb(window);var Qb=["http.0.st..rt.","network error occurred","send beacon","Content Security Policy","DOM Exception 18"];function Rb(a){throw a;}var Sb;function Tb(a){this.message=a}
var Ub=function(a){return function(b,c){c=void 0===c?!1:c;if(Sb)var d=new Sb(b);else r("Error",a.Error)?(Sb=a.Error,d=new a.Error(b)):(Sb=Tb,d=new Sb(b));c&&(d.unk=!0);return d}}(window),Vb=F("test",RegExp("^http."));function Wb(a){var b="";ka(a)?b=R(".",a):"string"===typeof a&&(b=a);return Ub("err.kn(2380)"+b)}var Xb=F("test",RegExp("^err.kn"));function Yb(a,b){return b?a(b):a()}var Zb=[];
function $b(a){a=I(a,"performance")||I(a,"webkitPerformance");var b=I(a,"timing.navigationStart"),c=I(a,"now");c&&(c=C(c,a));return[b,c]}function ac(a,b){var c=l(b||$b(a)),d=c.next().value;c=c.next().value;return!isNaN(d)&&y(c)?Math.round(c()+d):a.Date.now?a.Date.now():(new a.Date).getTime()}
function W(a,b,c){var d=c||Rb;return function(){var e=void 0;try{e=d.apply(null,arguments)}catch(k){var f=k,g="u.a.e",h="";f&&("object"===typeof f?(f.unk&&Rb(f),g=f.message,h="string"===typeof f.stack&&f.stack.replace(/\n/g,"\\n")||"n.s.e.s"):g=""+f);Xb(g)||$a(E(g,ha),Qb)||Vb(g)&&.1<=a.Math.random()||N(O(K,La(["jserrs",g,b,h]),Yb),Zb)}return e}}function bc(a,b){return function(){return W(arguments[0],a,b).apply(this,arguments)}}
function cc(a){return G(function(b,c){var d=l(c),e=d.next().value,f=d.next().value;d=f.ga;f=a[f.ka];b[e]=d?d(f):f;return b},{},fb(dc))}function ec(a,b){if(!b)return null;try{return a.JSON.parse(b)}catch(c){return null}}function fc(a,b){try{return a.JSON.stringify(b,null,void 0)}catch(c){return null}}function gc(a){try{return a.localStorage}catch(b){}return null}function hc(a,b){var c=gc(a);try{c.removeItem(b)}catch(d){}}
function ic(a,b){var c=gc(a);try{return ec(a,c.getItem(b))}catch(d){}return null}function jc(a,b,c){var d=gc(a);a=fc(a,c);if(!na(a))try{d.setItem(b,a)}catch(e){}}var kc=M(function(a){jc(a,"_ymBRC","1");var b="1"!==ic(a,"_ymBRC");b||hc(a,"_ymBRC");return b}),lc=M(function(a,b,c){var d=""+(void 0===c?"_ym":c)+(void 0===b?"":b);d&&(d+="_");return{ta:kc(a),l:function(e,f){var g=ic(a,""+d+e);return na(g)&&!z(f)?f:g},B:function(e,f){jc(a,""+d+e,f);return this},da:function(e){hc(a,""+d+e);return this}}});
function mc(a){if(A(a))return!1;a=a.nodeType;return 3===a||8===a}var nc=M(O(J("document"),E("createElement",Ga)));function oc(a,b,c){var d=z(c);z(b)&&d?(d=1,b=1073741824):d?d=1:(d=b,b=c);return a.Math.floor(a.Math.random()*(b-d))+d}function pc(a){return(10>a?"0":"")+a}function qc(a){var b=a.O;return 0!==b?b:ac(a.G,a.s)}
var rc=M(function(a){var b=tb(a),c=$b(a),d={G:a,O:0,s:c,sa:ac(a,c)},e=l(c);c=e.next().value;e=e.next().value;c&&e||b.g(a,["beforeunload","unload"],function(){0===d.O&&(d.O=ac(a,d.s))});return x(d)});function X(a,b,c,d){b=W(a,"d.err."+(d||"def"),b);return Ga("setTimeout",a)(b,c)}function sc(a,b){return function(c){return c(a,b)}}
function tc(a){function b(e){var f;if(f=I(c,d))if(c.nodeType){f=c.src;var g=I(c,"contentDocument.URL");f=f===g}else f=!0;f?e():X(a,E(e,b),100)}var c=void 0===c?a:c;var d=(c.nodeType?"contentWindow.":"")+"document.body";return x(function(e,f){b(f)})}function uc(a){var b=[],c={wa:b};c.g=O(F("push",b),E(c,K));c.X=O(w(Aa(a))(b),w(F("splice",b))(1),E(c,K));c.trigger=O(K,w(Yb),Ka(b));return c}J("postMessage");O(L,Q);O(rc,x(function(a){return-(new a.G.Date).getTimezoneOffset()}));
O(rc,x(function(a){a=new a.G.Date;return R("",N(pc,[a.getFullYear(),a.getMonth()+1,a.getDate(),a.getHours(),a.getMinutes(),a.getSeconds()]))}));O(rc,x(function(a){return Math.round(qc(a)/1E3)}));O(L,Q);E("px9zz6ry0gxo2cxlog",K);E("2380",K);O(J("navigator.cookieEnabled"),Oa);O(K,oc);J("devicePixelRatio");O(mb,Oa);O(nb,Oa);var vc=[],wc=[],xc=[],yc=[],zc=setTimeout;function Ac(){}function Bc(a,b){return function(){a.apply(b,arguments)}}
function Y(a){if(!(this instanceof Y))throw new TypeError("Promises must be constructed via new");if("function"!==typeof a)throw new TypeError("not a function");this.m=0;this.P=!1;this.v=void 0;this.D=[];Cc(a,this)}function Dc(a,b){for(;3===a.m;)a=a.v;0===a.m?a.D.push(b):(a.P=!0,Y.R(function(){var c=1===a.m?b.ia:b.ja;if(null===c)(1===a.m?Ec:Fc)(b.promise,a.v);else{try{var d=c(a.v)}catch(e){Fc(b.promise,e);return}Ec(b.promise,d)}}))}
function Ec(a,b){try{if(b===a)throw new TypeError("A promise cannot be resolved with itself.");if(b&&("object"===typeof b||"function"===typeof b)){var c=b.then;if(b instanceof Y){a.m=3;a.v=b;Gc(a);return}if("function"===typeof c){Cc(Bc(c,b),a);return}}a.m=1;a.v=b;Gc(a)}catch(d){Fc(a,d)}}function Fc(a,b){a.m=2;a.v=b;Gc(a)}function Gc(a){2===a.m&&0===a.D.length&&Y.R(function(){a.P||Y.ca(a.v)});for(var b=0,c=a.D.length;b<c;b++)Dc(a,a.D[b]);a.D=null}
function Hc(a,b,c){this.ia="function"===typeof a?a:null;this.ja="function"===typeof b?b:null;this.promise=c}function Cc(a,b){var c=!1;try{a(function(d){c||(c=!0,Ec(b,d))},function(d){c||(c=!0,Fc(b,d))})}catch(d){c||(c=!0,Fc(b,d))}}Y.prototype["catch"]=function(a){return this.then(null,a)};Y.prototype.then=function(a,b){var c=new this.constructor(Ac);Dc(this,new Hc(a,b,c));return c};
Y.prototype["finally"]=function(a){var b=this.constructor;return this.then(function(c){return b.resolve(a()).then(function(){return c})},function(c){return b.resolve(a()).then(function(){return b.reject(c)})})};
Y.all=function(a){return new Y(function(b,c){function d(h,k){try{if(k&&("object"===typeof k||"function"===typeof k)){var m=k.then;if("function"===typeof m){m.call(k,function(u){d(h,u)},c);return}}e[h]=k;0===--f&&b(e)}catch(u){c(u)}}if(!a||"undefined"===typeof a.length)return c(new TypeError("Promise.all accepts an array"));var e=Array.prototype.slice.call(a);if(0===e.length)return b([]);for(var f=e.length,g=0;g<e.length;g++)d(g,e[g])})};
Y.resolve=function(a){return a&&"object"===typeof a&&a.constructor===Y?a:new Y(function(b){b(a)})};Y.reject=function(a){return new Y(function(b,c){c(a)})};Y.race=function(a){return new Y(function(b,c){if(!a||"undefined"===typeof a.length)return c(new TypeError("Promise.race accepts an array"));for(var d=0,e=a.length;d<e;d++)Y.resolve(a[d]).then(b,c)})};Y.R="function"===typeof setImmediate&&function(a){setImmediate(a)}||function(a){zc(a,0)};
Y.ca=function(a){"undefined"!==typeof console&&console&&console.warn("Possible Unhandled Promise Rejection:",a)};var Z=window.Promise,Ic=t(Z,"Promise"),Jc=t(I(Z,"resolve"),"resolve"),Kc=t(I(Z,"reject"),"reject"),Lc=t(I(Z,"all"),"all");if(Ic&&Jc&&Kc&&Lc){var Mc=function(a){return new Promise(a)};Mc.resolve=C(Jc,Z);Mc.reject=C(Kc,Z);Mc.all=C(Lc,Z);Z=Mc}else Z=Y;function Nc(a){return a.N||a.V.length<=a.J}function Oc(a){a.N=!0}function Pc(a){a.N=!1}
function Qc(a){Nc(a)&&Rb(Ub("i"));var b=a.ea(a.V[a.J]);a.J+=1;return b}var Rc=v(function(a,b){for(var c=[];!Nc(b);){var d=Qc(b);a(d,function(e){return e(b)});c.push(d)}return c});function Sc(a,b){return function(c){var d=rc(a),e=d(qc);return Rc(function(f,g){d(qc)-e>=b&&g(Oc)})(c)}}
var Tc=/^\d+$/,Uc={id:function(a){a=""+(a||"0");Tc.test(a)||(a="0");try{var b=ab(a)}catch(c){b=0}return b},T:function(a){return""+(a||0===a?a:"0")},fa:Pa,oa:Pa},dc=G(function(a,b){var c=l(b),d=c.next().value;c=c.next().value;a[d]={ka:c,ga:Uc[d]};return a},{},fb({id:"id",oa:"ut",T:"type",va:"ldc",fa:"nck",ra:"url",qa:"referrer"}));C(Z.reject,Z,Wb());var Vc=M(bc("dc.init",function(){return{log:p,warn:p,error:p}}),L);function Wc(a,b,c,d){Vc(a,b).log(c,d)}
function Xc(a,b){var c=vb(a).l("counters",{}),d=Q(b);return c[d]}function Yc(a,b){b=void 0===b?p:b;var c=void 0===c?!1:c;var d=uc(a);if(q&&y(q.push)){var e=q.push;q.push=function(){var f=B(arguments),g=l(f).next().value;c&&d.trigger(g);f=e.apply(q,f);c||d.trigger(g);return f};b({ha:d,unsubscribe:function(){q.push=e}});N(d.trigger,q)}}function Zc(a,b){return function(c){var d=c[a];d?(d.Z=!0,d.Y(b)):c[a]={promise:Z.resolve(b),Z:!0,Y:p}}}
var $c=v(function(a,b){if(!b[a]){var c,d=new Z(function(e){c=e});b[a]={Y:c,promise:d,Z:!1}}return b[a].promise}),ad=M(O(function(){return{}},x));function bd(a,b){ad()(Zc(a,b))}function cd(a,b){var c=Q(a);return ad()($c(c)).then(b)}
function dd(a,b){if(a.postMessage&&!a.attachEvent){var c=tb(a),d="__ym__promise_"+oc(a)+"_"+oc(a),e=p;e=c.g(a,["message"],W(a,"as",function(f){try{var g=f.data}catch(h){return}g===d&&(e(),f.stopPropagation&&f.stopPropagation(),b())}));a.postMessage(d,"*")}else X(a,b,0,"as")}var ed=[],fd=!1,gd=!1;function hd(a){if(ed.length){var b=ed.shift();gd?b():X(a,b,100)}else fd=!1}
function id(a,b,c){c=void 0===c?1:c;var d=void 0===d?Sc:d;gd=Infinity===c;return x(function(e,f){function g(){try{var k=b(d(a,c));h=h.concat(k)}catch(m){return e(m)}b(Pc);if(b(Nc))return f(h),hd(a);gd?(b(d(a,1E4)),f(h),hd(a)):X(a,g,100)}var h=[];fd?ed.push(g):(fd=!0,g())})}function jd(a,b,c,d,e){d=void 0===d?1:d;e=void 0===e?"itc":e;b=x({V:b,ea:c||K,N:!1,J:0});id(a,b,d)(sc(W(a,e),p))}
function kd(a,b,c,d,e){function f(k){return y(d)?d(k)?a.NodeFilter.FILTER_ACCEPT:a.NodeFilter.FILTER_REJECT:a.NodeFilter.FILTER_ACCEPT}e=void 0===e?-1:e;var g=void 0===g?!1:g;var h=f(b);if(y(c)&&(g||h===a.NodeFilter.FILTER_ACCEPT)&&(h&&c(b),!mc(b)))for(b=a.document.createTreeWalker(b,e,d?{acceptNode:f}:null,!1);b.nextNode()&&!1!==c(b.currentNode););}var ld=M(function(a){return R("[^\\d<>]*",a.split(""))}),md=M(function(a){return new RegExp(ld(a),"g")});
function nd(a){return new RegExp("(?:"+R("|",N(ld,gb(a)))+")")}function od(a){var b={7:"8",8:"7"};return 11===a.length&&b[a[0]]?""+b[a[0]]+a.slice(1):a}function pd(a,b){for(var c=[],d=a.split(""),e=b.split(""),f=0,g=0;g<a.length&&!(f>=e.length);g+=1){var h=d[g];"0"<=h&&"9">=h?(c.push(e[f]),f+=1):c.push(d[g])}return R("",c)+b.slice(f+1)}function qd(){return D([function(a,b){var c=l(N(V,b)),d=c.next().value;c=c.next().value;a[d]={A:c,K:b};var e=od(d);e!==d&&(a[e]={A:od(c),K:b});return a},{}],G)}
function rd(a,b,c){if(!c)return[];var d=[],e=nd(b),f=["script","style"];kd(a,c,function(g){var h=I(g,"parentNode.nodeName")||"";g===c||Wa(h.toLowerCase(),f)||(h=Ta(e.exec(g.textContent||"")||[]),N(function(k){var m=V(k);z(b[m])||d.push({M:"text",C:g,I:m,A:pd(k,b[m].A),ma:g.textContent||""})},h))},function(g){return e.test(g.textContent||"")?1:0},a.NodeFilter.SHOW_TEXT);return d}
function sd(a,b){var c=a.document.body;if(!c)return[];var d=nd(b);return G(function(e,f){var g=I(f,"href");try{var h=decodeURI(g||"")}catch(S){h=""}var k=h;if("tel:"===k.slice(0,4)){var m=l(d.exec(k)||[]).next().value;h=m?V(m):"";var u=b[h];z(u)||!h&&"*"!==u.K[0]||(e.push({M:"href",C:f,I:h,A:pd(m,b[h].A),ma:g}),g=V(k.slice(4)),g=qd()([h?u.K:[g,""]]),ub(e,rd(a,g,f)))}return e},[],Xa(c.querySelectorAll("a")))}
function td(a,b,c){function d(k){return e(a,b,k)?h[k.I]&&h[k.I].K:null}var e=c.aa,f={},g=void 0===c.W?(f.href=!0,f.text=!0,f):c.W,h;return function(k){return new Z(function(m,u){k&&k.length||u();h=qd()(k);tc(a)(sc(E({j:[],s:0},m),function(){var S=rc(a),ra=S(qc),T=g.href?sd(a,h):[],sa=g.text?rd(a,h,a.document.body):[];m({j:Sa(ka,Ta(N(d,T.concat(sa)))),s:S(qc)-ra})}))})}}function ud(a,b){tb(a).g(a,["load"],b.trigger)}
function vd(a,b){tc(a)(sc(p,function(){var c=a.document.body,d={};d=(d.attributes=!0,d.childList=!0,d.subtree=!0,d);r("MutationObserver",a.MutationObserver)&&(new MutationObserver(b.trigger)).observe(c,d)}))}function wd(a,b){function c(){e=0;f&&(f=!1,e=X(a,c,1E3),d.trigger(g))}var d=uc(a),e,f=!1,g;b.g(function(h){f=!0;g=h;e||c();return p});return d}var xd=/\S/;
function yd(a,b,c,d){function e(){N(function(m){m.style&&P(m.style,{opacity:""})},Xa(c.childNodes));if(b){var k=Xc(a,b);k&&k.extLink("tel:"+d,{})}g();h()}var f=tb(a),g=p,h=p;g=f.g(c,["mouseenter"],function(k){if(k.target===c){var m=X(a,e,200,"ph.h.e");h();h=f.g(c,["mouseleave"],function(u){u.target===c&&Ga("clearTimeout",a)(m)})}})}
var zd=E(["style","display:inline;margin:0;padding:0;font-size:inherit;color:inherit;line-height:inherit"],function(a,b){b=void 0===b?{}:b;if(!a||1>a.length)return b;G(function(c,d,e){if(e===a.length-1)return c;e===a.length-2?c[d]=a[e+1]:H(c,d)||(c[d]={});return c[d]},b,a);return b});
function Ad(a,b,c){var d=nc(a),e=c.C,f=c.I,g=e.parentNode,h=e.textContent;if(!("text"===c.M&&h&&d&&g))return!1;c=d("small");zd(c);var k=Db(h).length;N(F("appendChild",c),G(function(m,u){var S=m.nodes,ra=m.ba,T=d("small");T.innerHTML=u;var sa=xd.test(u);zd(T);sa&&(T.style.opacity=""+(k-ra-1)/k);S.push(T);return{nodes:S,ba:ra+(sa?1:0)}},{nodes:[],ba:0},h).nodes);yd(a,b,c,f);g.insertBefore(c,e);e.textContent="";return!0}
function Bd(a,b,c){var d={};b=td(a,b,{aa:Ad,W:(d.href=!0,d)});c=Ta(N(function(f){return"*"===f?f:V(f)},c));var e=N(O(K,F("concat",[""]),Ma("reverse"),Yb),c);c=uc(a);d=wd(a,c);b=E(e,b);d.g(b);ud(a,c);vd(a,c);b()}
var Cd=M(function(a){var b;(b=ib(a))||(b=!(r("querySelectorAll",I(a,"Element.prototype.querySelectorAll"))&&a.document.querySelectorAll));return b}),Dd=bc("phc.h",function(a,b){if(!ob(a)&&!Cd(a))return cd(b,function(c){if(!I(c,"settings.phchange")){var d=lc(a),e=ha(U(a).search,"_ym_hide_phones=1")||d.l("hide_phones",0);c=I(c,"settings.phhide");e&&!c&&(c=["*"],d.B("hide_phones",1));c&&Bd(a,b,c)}})["catch"](W(a,"phc.hs"))}),Ed=/[\*\.\?\(\)]/g,Fd=M(function(a,b,c){try{var d=c.replace("\\s"," ").replace(Ed,
"");b={};Vc(a,"").warn("nnw",(b.name=d,b))}catch(e){}},L),Gd=bc("r.nn",function(a){Pb(a)&&Yc(a,function(b){b.ha.g(function(c){var d=l(c);c=d.next().value;d=d.next().value;Fd(a,d,c);q.splice(100)})})});E(Wb("ccf"),Rb);
function Hd(a,b,c,d,e){if(b.F&&b.H&&(b.F===a.F&&b.H===a.H||P(a,b,{j:{},L:!0}),0<e&&ub(a.s,[e]),N(function(f){var g=l(f);f=g.next().value;g=g.next().value;var h={},k={};P(a.j,(k[f]=(h[g]=+(a.j[f]&&a.j[f][g]?a.j[f][g]:0),h),k))},d),N(function(f){var g=l(f);f=g.next().value;g=g.next().value;var h={},k={};P(a.j,(k[f]=(h[g]=1+(a.j[f]?a.j[f][g]:0),h),k))},c),a.U&&(a.L||c.length))){if(b=Xc(a.G,a.S))c={},b.params("__ym","phc",(c.clientId=a.F,c.orderId=a.H,c.service_id=a.$,c.phones=a.j,c.performance=a.s,c));
a.L=!1}}var Id=M(td);function Jd(a,b,c){a=md(c.I);if("href"===c.M){var d=c.C;b=d.href;c=b.replace(a,c.A);if(b!==c)return d.href=c,!0}else if((b=null===(d=c.C.textContent)||void 0===d?void 0:d.replace(a,c.A))&&b!==c.C.textContent)return c.C.textContent=b,!0;return!1}var Kd=M(ec,L);
function Ld(a,b,c){b=Nb(a,void 0,b);b=Kd(a,b.l("phc_settings")||"");var d=I(b,"clientId"),e=I(b,"orderId"),f=I(b,"service_id"),g=I(b,"phones")||[];return d&&e&&g&&f?Id(a,c.S,{aa:Jd})(g).then(function(h){return Hd(c,{F:d,H:e,$:f},h.j,g,h.s)})["catch"](p):Z.resolve()}
var Md=bc("phc.p",function(a,b){if(!Cd(a))return cd(b,function(c){var d=b.id,e=Nb(a,void 0,d),f=e.l("phc_settings")||"";if(c=I(c,"settings.phchange")){var g=fc(a,c)||"";g!==f&&e.B("phc_settings",g)}else f&&(c=Kd(a,f));e=I(c,"clientId");f=I(c,"orderId");c=I(c,"phones")||[];e&&f&&c.length&&(f={F:"",H:"",$:0,j:{},s:[],U:!1,L:!0,G:a,S:b},P(f,{U:!0}),Ld(a,d,f),c=uc(a),e=wd(a,c),d=C(Ld,null,a,d,f),e.g(d),vd(a,c))})}),Nd=vb(window),Od=["tag_phone","js"].shift();vb(window);wc.push(Dd);Eb.push("_ym_debug");
yc.unshift(Gd);wc.push(Md);
var Pd=function(){var a=window;N(w(Yb)(a),yc);return W(window,"m."+Od,function(b,c,d){var e=cc(b);"2380"!==d&&Rb(Ub("m.vc."+Od));b=N(K,xc);d=Q(e);var f={};f=D([a,d,"imnc",(f.key=d,f.module="tag_phone.js",f)],Wc);c&&bd(d,c);if(Nd.l("counters",{})[d]){N(function(k){k(a,e)},vc);var g=[],h=function(k){k&&(y(k)?g.push(k):y(k.then)?k.then(h):!na(k)&&!z(k)&&"[object Object]"===Object.prototype.toString.call(k)&&k.u&&g.push(k.u))};c=function(k){k=k(a,e);h(k)};dd(a,D([a,b,c,1,"a.i"],jd));N(c,wc);return D([Yb,
g],N)}f()})}(),Qd=Nd.l("ytmm",{});if(!Qd[Od]){var Rd={};Qd[Od]=(Rd.init=Pd,Rd);Nd.B("ytmm",Qd)};}).call(this);
